project_id = "nvsufriurpjcrrnaxlfl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://nvsufriurpjcrrnaxlfl.supabase.co"
additional_redirect_urls = ["https://lovable.app"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your code is {{ .Code }}"

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 25
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "https://nvsufriurpjcrrnaxlfl.supabase.co"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcp.json"

[functions.bulk-upload-codes]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.create-payu-payment]
verify_jwt = true

[functions.payu-callback]
verify_jwt = false

[functions.create-shipment]
verify_jwt = false

[edge_runtime]
enabled = true
ip_version = "ipv4"