// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvsufriurpjcrrnaxlfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52c3Vmcml1cnBqY3JybmF4bGZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzkyMzIsImV4cCI6MjA2NzE1NTIzMn0.R3ppGADNFin7FEOQDSk0QBN-qOI09o_jksMzI2T-mdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});